config/routes.rb
Rails.application.routes.draw do
  resources :styles

  get 'auth/:provider/callback', to: 'sessions#create_oauth'

  resources :memberships do
    post 'confirm_member', on: :member
  end
  delete 'memberships', to: 'memberships#destroy'

  resources :beer_clubs

  resources :users do
    post 'toggle_frozen', on: :member
  end

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :beers
  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'

  get 'brewerylist', to:'breweries#brewerylist'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  root 'breweries#index'

  resources :ratings, only: [:index, :new, :create, :destroy]

  resource :session, only: [:new, :create, :delete]

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships

  def to_s
    "#{self.name}, #{self.city}"
  end

  def members
    memberships.is_confirmed.collect {|m| m.user}
  end

  def is_member?(user)
    members.include? user
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :has_admin_role, only: [:destroy]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.beer_club = @beer_club
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        @membership = Membership.new
        @membership.beer_club = @beer_club
        @membership.user = current_user
        @membership.confirmed = true
        @membership.save
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.number_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club, class: "btn btn-info" %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beer Clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= beer_club.name %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <td><%= link_to 'Show', beer_club, class: "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_beer_club_path(beer_club), class: 'btn btn-success' if current_user %></td>
        <td><%= link_to 'Destroy', beer_club, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' if current_user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer club', new_beer_club_path, class:'btn btn-primary' if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<h1><%= @beer_club.name %>, <%= @beer_club.city %></h1>

<p>
  Founded: <%= @beer_club.founded %>
</p>

<p>
  <% if @beer_club.users.empty? %>
      has no memberships
  <% else %>
    <h2>members</h2>

    <ul>
      <% @beer_club.memberships.is_confirmed.each do |membership| %>
          <li> <%= link_to membership.user.username, user_path(membership.user) %></li>
      <% end %>
    </ul>
<% end %>
</p>

<p>
<h2>Outstanding applicants</h2>

<ul>
  <% @beer_club.memberships.is_applicant.each do |membership| %>
      <li>
        <%= link_to membership.user.username, user_path(membership.user) %>
        <% if @beer_club.is_member? current_user %>
            <%= link_to 'confirm', confirm_member_membership_path(membership), method: :post, class: 'btn btn-success' %>
        <% end %>
      </li>
  <% end %>
</ul>
</p>

<% if current_user and not @beer_club.users.include?(current_user)  %>
    <%= form_for(@membership) do |f| %>
        <%= f.hidden_field :beer_club_id %>
        <%= f.submit value:"join the club", class:'btn btn-primary' %>
    <% end %>
<% end %>

<% if current_user and @beer_club.users.include?(current_user) %>
    <%= form_for(@membership, method: "delete") do |f| %>
        <%= f.hidden_field :beer_club_id %>
        <%= f.submit value: "end the membership", class:'btn btn-danger' %>
    <% end %>
<% end %>


<%= link_to 'Edit', edit_beer_club_path(@beer_club), class: 'btn btn-success' if current_user %> |
<%= link_to 'Back', beer_clubs_path %>