config/routes.rb
Rails.application.routes.draw do
  resources :styles

  get 'auth/:provider/callback', to: 'sessions#create_oauth'

  resources :memberships do
    post 'confirm_member', on: :member
  end
  delete 'memberships', to: 'memberships#destroy'

  resources :beer_clubs

  resources :users do
    post 'toggle_frozen', on: :member
  end

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :beers
  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'

  get 'brewerylist', to:'breweries#brewerylist'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  root 'breweries#index'

  resources :ratings, only: [:index, :new, :create, :destroy]

  resource :session, only: [:new, :create, :delete]

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage

  has_secure_password

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  validates :username, uniqueness: true
  validates :username, length: {
                         minimum: 3,
                         maximum: 15
                     }
  validates :password, length: {
                         minimum: 4
                     }
  validates_format_of :password, with: /(?=.*[\d])/, message: "password must contain at least one digit"
  validates_format_of :password, with: /(?=.*[A-ZÅÄÖ])/, message: "password must contain at least one upper case letter"

  def self.most_active_raters(n)
    all.sort_by{ |u| -(u.ratings.count||0)}.first(n)
  end

  def favorite_beer
    return nil if ratings.empty?
    # ratings.sort_by{ |r| r.score }.last.beer
    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_style
    return nil if ratings.empty?
    beers.group(:style).average(:score).max_by { |name, score| score }.first.name
  end

  def favorite_brewery
    return nil if ratings.empty?
    beers.group(:brewery).average(:score).max_by { |name, score| score }.first
  end

  def confirmed_in
    memberships.is_confirmed.collect { |m| m.beer_club }.compact
  end

  def applicant_in
    memberships.is_applicant.collect { |m| m.beer_club }.compact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:beers).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user == current_user
      @user.destroy
      session[:user_id] = nil
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      format.html { redirect_to user_path @user, notice: 'you dont have the rights to do that' }
    end
  end

  def toggle_frozen
    user = User.find(params[:id])
    user.update_attribute :disabled, (not user.disabled)

    new_status = user.disabled ? "disabled" : "enabled"

    redirect_to :back, notice: "account #{user.username} #{new_status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, html: {class: 'navbar-form'} do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="form-group">
    <% if @user.new_record? %>
        <div class="field">
          <%= f.text_field :username, class: "form-control", placeholder: "username" %>
        </div>

        <div class="field">
          <%= f.password_field :password, class: "form-control", placeholder: "password" %>
        </div>

    <% else %>
    <div class="field">
      <%= f.password_field :password, class: "form-control", placeholder: "password" %>
    </div>
    <% end %>
    <div class="field">
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "confirm password" %>
    </div>
    <div class="actions">
      <%= f.submit class:'btn btn-primary' %>
    </div>
        </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form' %>

<%= link_to 'Show', @user, class: "btn btn-info" %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Username</th>
    <th> rated beers </th>
    <th> total ratings </th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td>
          <% if current_user && current_user.admin && user.disabled? %>
              <span class="label label-info">account frozen</span>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class:'btn btn-primary' %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
  <% if @user.disabled %>
      <span class="label label-info">frozen</span>
  <% end %>
</p>

<p>
  <% if @user.ratings.empty? %>
      has made no ratings and has no favorite style or favorite brewery
  <% else %>
      <%= "Has made #{pluralize(@user.ratings.count, 'rating')}, average #{round(@user.average_rating)}" %>

      <p>
      <strong>Favorite style:</strong>
      <%= @user.favorite_style %>
      </p>

      <p>
      <strong>Favorite brewery:</strong>
      <%= link_to @user.favorite_brewery.name, @user.favorite_brewery %>
      </p>

      <h2>ratings</h2>

      <ul>
        <% @user.ratings.each do |rating| %>
            <li> <%= rating.to_s %>
              <% if @user == current_user %>
                  <%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </li>
        <% end %>
      </ul>
  <% end %>
  </p>

  <p>
    <% if @user.memberships.empty? %>
        has no memberships
    <% else %>
        <%= "Has #{pluralize(@user.memberships.count, 'membership')}" %>

      <h2>member of</h2>

      <ul>
        <% @user.confirmed_in.each do |beerclub| %>
            <li> <%= link_to beerclub.to_s, beer_club_path(beerclub) %></li>
        <% end %>
      </ul>

    <h2>applied membership of</h2>

    <ul>
      <% @user.applicant_in.each do |beerclub| %>
          <li> <%= link_to beerclub.to_s, beer_club_path(beerclub) %></li>
      <% end %>
    </ul>
  <% end %>
  </p>

  <% if current_user && current_user.admin %>
    <%= link_to (@user.disabled ? "enable account" : "freeze account"), toggle_frozen_user_path(@user), method: :post, class: "btn btn-primary" %>
  <% end %>

  <% if @user == current_user %>
      <%= link_to 'Destroy',@user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %> |
      <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-success' %> |
  <% end %>
  <%= link_to 'Back', users_path %>